### ISSUE TITLE
Integrate authenticate pages

### ISSUE THREAD

**Issue by TheMindset** [TheMindset/meet_my_class#1]
**WHY**

Improve UX Design 

**TODO**

* [ ] page for signup as teacher 
* [ ] page for signup as student
* [ ] page for login as teacher 
* [ ] page for login as student
* [ ] page for recovery password as teacher 
* [ ] page for recovery password as student

**MUST HAVE**

* [ ] Have authentice pages and beautiful and a flash messages for animate all that
