### ISSUE TITLE
Root page

### ISSUE THREAD

**Issue by TheMindset** [TheMindset/meet_my_class#2]
**WHY**

Built the app
Improve UX Design 

**TODO**

* [x] Integrate the page from template
* [x] Display all classes
* [x] restrict details class if teacher or student login
* [x] add bouton for teacher namespace

**MUST HAVE**

* [x] Have wonderful home page
