### ISSUE TITLE
Integrate Sidebar

### ISSUE THREAD

**Issue by TheMindset** [TheMindset/meet_my_class#3]
**WHY**

Built the app
Improve UX Design 

**TODO**

* [ ] Integrate the sidebar and navbar from template
* [ ] add button for profile
* [ ] add button for teacher namespaces if he is login

**MUST HAVE**

* [ ] Have wonderful sidebar
