### ISSUE TITLE
Classes details page

### ISSUE THREAD

**Issue by TheMindset** [TheMindset/meet_my_class#4]
**WHY**

Built the app
Improve UX Design 

**TODO**

* [ ] show how are in the classes
* [ ] add button for join class if the teacher invite the student
* [ ] see all current class where student join (if so pursue step)
* [ ] if current teacher has classes possibility to see it

**MUST HAVE**

* [ ] Have wonderful details page
